server {
    listen 80;
    server_name localhost;

    # Ruta donde Nginx encontrará tus archivos Flutter Web
    root /usr/share/nginx/html;
    index index.html;

    # Regla para index.html: no cachear agresivamente
    # Esto asegura que el navegador siempre solicite la última versión de index.html
    location = /index.html {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }

    # Regla para los assets (JS, Wasm, CSS, imágenes): cachear agresivamente
    # Esto es crucial porque Flutter añade hashes a sus nombres,
    # así que si cambian, el navegador los descargará como nuevos.
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|woff|woff2|ttf|svg|eot|wasm)$ {
        add_header Cache-Control "public, max-age=31536000, immutable";
        expires 1y; # Opción alternativa/complementaria a max-age para algunos navegadores
        try_files $uri $uri/ =404;
    }

    # Manejo de las rutas de Flutter (fallback a index.html para rutas SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }
}